/*
* appActions.js
* */

/**************** APP ACTIONS **************************/
export const FETCH_USER_FIRSTNAME = 'FETCH_USER_FIRSTNAME';
export const SET_ACCOUNT_ID = 'SET_ACCOUNT_ID';
export const SET_ACCOUNT_ID_NAME = 'SET_ACCOUNT_ID_NAME'; // set account's id and user's name
export const SET_DEFAULT_USER_ACCOUNT_ID  = 'SET_DEFAULT_USER_ACCOUNT_ID';
export const SET_DEFAULT_USER_ACCOUNT_ID_FAILED = 'SET_DEFAULT_USER_ACCOUNT_ID_FAILED';
export const FETCH_USER_FIRSTNAME_FAILED = 'FETCH_USER_FIRSTNAME_FAILED';
export const LOGIN_USER = 'LOGIN_USER'; //login with user id
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_LOGIN = 'USER_LOGIN';//login with username and password
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

/**************** SURVEY ACTIONS **************************/
export const CREATE_SURVEY = 'CREATE_SURVEY';
export const FETCH_SURVEY = 'FETCH_SURVEY';
export const SET_SURVEY_ID = 'SET_SURVEY_ID';
export const EDIT_SURVEY_DATA = 'EDIT_SURVEY_DATA';
export const EDIT_SURVEY = 'EDIT_SURVEY';
export const SAVE_SURVEY = 'SAVE_SURVEY';
export const SAVE_NEW_SURVEY = 'SAVE_NEW_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const LIST_SURVEYS = 'LIST_SURVEYS';
export const SURVEY_LIST = 'SURVEY_LIST';
export const SURVEY_LIST_FAILED = 'SURVEY_LIST_FAILED';
// export const RESET_SURVEY = 'RESET_SURVEY';
export const CREATE_SURVEY_FAILED = 'CREATE_SURVEY_FAILED';
export const DELETE_SURVEY_FAILED = 'DELETE_SURVEY_FAILED';
// export const EDIT_SURVEY_DATA_FAILED = 'EDIT_SURVEY_DATA_FAILED';
// export const EDIT_SURVEY_FAILED = 'EDIT_SURVEY_FAILED';
export const SAVE_SURVEY_FAILED = 'SAVE_SURVEY_FAILED';
// export const DELETE_SURVEY_FAILED = 'DELETE_SURVEY_FAILED';
export const SAVE_SURVEY_RESULTS_FAILED = 'SAVE_SURVEY_RESULTS_FAILED';
export const FETCH_SURVEY_RESULTS_FAILED = 'FETCH_SURVEY_RESULTS_FAILED';
export const LIST_SURVEYS_FAILED = 'LIST_SURVEYS_FAILED';
export const FETCH_SURVEY_FAILED = 'FETCH_SURVEY_FAILED';
export const SAVE_SURVEY_RESULTS = 'SAVE_SURVEY_RESULTS';
export const FETCH_SURVEY_RESULTS = 'FETCH_SURVEY_RESULTS';
export const SET_SURVEY_TITLE = 'SET_SURVEY_TITLE';
export const SET_QUESTION_STRING = 'SET_QUESTION_STRING';
export const SET_ANSWER_STRING = 'SET_ANSWER_STRING';
export const GET_SURVEY_AND_QUESTIONS = 'GET_SURVEY_AND_QUESTIONS';
export const GET_SURVEY_AND_QUESTIONS_FAILED = 'GET_SURVEY_AND_QUESTIONS_FAILED';

/**************** QUESTION ACTIONS **************************/
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const CANCEL_EDIT_QUESTION = 'CANCEL_EDIT_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const SHOW_ANSWERS = 'SHOW_ANSWERS';
export const HIDE_ANSWERS = 'HIDE_ANSWERS';
export const CREATE_QUESTION_FAILED = 'CREATE_QUESTION_FAILED';
export const ADD_QUESTION_FAILED = 'ADD_QUESTION_FAILED';
export const SAVE_QUESTION_FAILED = 'SAVE_QUESTION_FAILED';
export const DELETE_QUESTION_FAILED = 'DELETE_QUESTION_FAILED';

/**************** ANSWER ACTIONS **************************/
export const CREATE_ANSWER = 'CREATE_ANSWER';
// export const ADD_ANSWER = 'ADD_ANSWER';
export const EDIT_ANSWER = 'EDIT_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const SAVE_ANSWER = 'SAVE_ANSWER';
export const CANCEL_EDIT_ANSWER = 'CANCEL_EDIT_ANSWER';
export const CREATE_ANSWER_FAILED = 'CREATE_ANSWER_FAILED';
// export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const EDIT_ANSWER_FAILED = 'EDIT_ANSWER_FAILED';
export const DELETE_ANSWER_FAILED = 'DELETE_ANSWER_FAILED';
export const SAVE_ANSWER_FAILED = 'SAVE_ANSWER_FAILED';
// export const CANCEL_ANSWER_FAILED = 'CANCEL_ANSWER_FAILED';

/**************** USER ANSWER ACTIONS **************************/
export const REGISTER_ANSWER = 'REGISTER_ANSWER';
export const REGISTER_ANSWER_FAILED = 'REGISTER_ANSWER_FAILED';

/**************** USER ACTIONS **************************/
export const FETCH_USER = 'FETCH_USER';
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const CANCEL_EDIT_USER = 'CANCEL_EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const LIST_USERS = 'LIST_USERS';
export const SAVE_USER = 'SAVE_USER';
export const RESET_USER = 'RESET_USER';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
// export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const LIST_USERS_FAILED = 'LIST_USERS_FAILED';
export const SAVE_USER_FAILED = 'SAVE_USER_FAILED';
export const SELECT_USER = 'SELECT_USER';

/**************** ACCOUNT ACTIONS **************************/
export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CREATE_NEW_ACCOUNT = 'CREATE_NEW_ACCOUNT';
export const EDIT_ACCOUNT  = 'EDIT_ACCOUNT';
export const CANCEL_EDIT_ACCOUNT  = 'CANCEL_EDIT_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const LIST_ACCOUNTS = 'LIST_ACCOUNTS';
export const SAVE_ACCOUNT = 'SAVE_ACCOUNT';
export const RESET_ACCOUNT = 'RESET_ACCOUNT';
export const FETCH_ACCOUNT_FAILED = 'FETCH_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
// export const EDIT_ACCOUNT_FAILED  = 'EDIT_ACCOUNT_FAILED';
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';
export const LIST_ACCOUNTS_FAILED = 'LIST_ACCOUNTS_FAILED';
export const SAVE_ACCOUNT_FAILED = 'SAVE_ACCOUNT_FAILED';
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
